version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: rankus-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rankus
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
