spring:
  config:
    activate:
      on-profile: default

  datasource:
    url: jdbc:mysql://localhost:3306/rankus?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          charset_name: UTF-8       # DDL에 DEFAULT CHARSET=UTF-8을 붙여줌
          connection:
            charSet: UTF-8            # Hibernate 내부 커넥션에도 UTF-8 사용

  sql:
    init:
      mode: always

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

security:
  jwt:
    secret: default-jwt-secret
    expiration-ms: 3600000  # 1시간 (밀리초 단위)
