spring:
  config:
    activate:
      on-profile: secure

  datasource:
    url: jdbc:mysql://localhost:3306/rankus?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop  # 개발 환경에서는 create-drop을 사용하여 매번 스키마를 초기화
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8080

security:
  jwt:
    secret: local-jwt-secret   # 로컬용 테스트 비밀키
    expiration-ms: 3600000  # 1시간 (밀리초 단위)

