spring:
  config:
    activate:
      on-profile: aws

  datasource:
    url: ${SPRING_DATASOURCE_URL}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop  # 개발 환경에서는 create-drop을 사용하여 매번 스키마를 초기화
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection.characterEncoding: UTF-8
        connection.CharSet: UTF-8
        connection.useUnicode: true

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}